### ISSUE TITLE
Interpretation der Schriftgröße in Browsern

### ISSUE THREAD

**Issue by gadgec** [conterra/mapapps-imprint-privacy#1]
Die Beschriftung der Button wird im Firefox 61 und im IE 11 unterschiedlich umgesetzt.
Im Firefox wird die _font-size: initial_ aus der styles.css des Bundles verwendet und im IE die _font-size: 1.75rem_ des App-Themes. Im Ergebnis ist der Text im IE 28px und im Firefox 16px groß.

Wenn im Firefox das Farbschema über den ThemeSelector geändert wird, ändert sich die Größe der Beschriftung auf 28px trotz CSS font-size: initial.

**Comment by matthiasstein** [comment]
The problem still exists in apps of Linie 4 in Internet Explorer 11, which does not support the CSS keyword initial.
